ARG SCRIPT=./zsh_home_install.sh

FROM archlinux:latest
COPY --chmod=777 $SCRIPT /zsh.sh
RUN pacman -Syu --needed --noconfirm sudo git zsh base base-devel && \
    useradd -m -G wheel -s /bin/bash kosh && \
    sed -i 's/# %wheel ALL=(ALL:ALL) NOPASSWD: ALL/%wheel ALL=(ALL:ALL) NOPASSWD: ALL/g' /etc/sudoers
RUN su - kosh -c "git clone https://aur.archlinux.org/yay-bin && cd yay-bin && yes | makepkg -si && cd .. && rm -rf yay-bin && yay -Y --gendb && yes | yay -Syu --devel && yay -Y --devel --save && yay --editmenu --diffmenu=false --save"
RUN /zsh.sh

FROM fedora:latest
COPY $SCRIPT /zsh.sh
RUN dnf install sudo && \
    chmod 755 ./zsh_home_install.sh && \
    useradd -m -G wheel -s /bin/bash test && \
    sed -i 's/# %wheel	ALL=(ALL)	NOPASSWD: ALL/%wheel	ALL=(ALL)	NOPASSWD: ALL/g' /etc/sudoers
USER test
ENV TERM=xterm
RUN bash -c /zsh.sh

FROM debian: latest
COPY --chmod=777 $SCRIPT /zsh.sh
RUN apt update -y && apt upgrade -y && \
    apt install zsh sudo -y && \
    useradd -m -G wheel -s /bin/bash test && \
    sed -i 's/# %wheel	ALL=(ALL)	NOPASSWD: ALL/%wheel	ALL=(ALL)	NOPASSWD: ALL/g' /etc/sudoers
RUN cat /etc/sudoers
USER test
RUN /zsh.sh

