name: aur_builder_build_and_upload

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: "0 0 * * *"

jobs:

  aur_build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: docker login
      env:
        DOCKERHUB_USERNAME: ${{secrets.DOCKERHUB_USERNAME}}
        DOCKERHUB_TOKEN: ${{secrets.DOCKERHUB_TOKEN}}
      run: |
        docker login -u $DOCKERHUB_USERNAME -p $DOCKERHUB_TOKEN 
    - name: Build the Docker image
      run: DOCKER_BUILDKIT=1 docker build . --file aur_helper.Dockerfile --tag deathmond1987/aur_helper:latest
      
    - name: Docker Push
      run: docker push deathmond1987/aur_helper:latest
